Fix NullPointerException in EpgsdataFragment()
... onActivityCreated() {
mView = (LinearLayout) mActivity.findViewById(R.id.epgsdata_main);
...
}

mView was null because we have to request it from epgsdata_fragment instead of mActivity. Thanks to the guys from #android-dev on FreeNode!

    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.androvdr/de.androvdr.activities.EpgsdataActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.findViewById(int)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.findViewById(int)' on a null object reference
            at de.androvdr.controllers.EpgsdataController.<init>(EpgsdataController.java:118)
            at de.androvdr.fragments.EpgsdataFragment.onActivityCreated(EpgsdataFragment.java:77)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1970)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1189)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2001)
            at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:507)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
            at android.app.Activity.performStart(Activity.java:6006)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)